local colors = {
  white = '#FFFFFF',
  black = '#000000',

  -- This color is not part of `ayu` but matches the default style applied in VSCode.
  lsp_inlay_hint = '#969696',
}

--- Generate colors based `vim.o.background` and a variant.
---@param mirage boolean: Whether to use `mirage` variant when `vim.o.background` is dark.
function colors.generate(mirage)
  if vim.o.background == 'dark' then
    if mirage then
      colors.accent = '#FFCC66'
      colors.bg = '#242936'
      colors.fg = '#CCCAC2'
      colors.line = '#1A1F29'
      colors.ui = '#707A8C'
      colors.ui_bg = '#1F2430'
      colors.ui_line = '#171B24'

      colors.tag = '#5CCFE6'
      colors.func = '#FFCD66'
      colors.entity = '#73D0FF'
      colors.string = '#D5FF80'
      colors.regexp = '#95E6CB'
      colors.markup = '#F28779'
      colors.keyword = '#FFAD66'
      colors.special = '#D9BE98'
      colors.comment = '#6E7C8F'
      colors.constant = '#DFBFFF'
      colors.operator = '#F29E74'
      colors.error = '#FF6666'
      colors.warning = '#FFA759'
      colors.lsp_parameter = '#D3B8F9'

      colors.panel_bg = '#282E3B'
      colors.panel_shadow = '#161922'
      colors.panel_border = '#101521'
      colors.gutter_normal = '#4A505A'
      colors.gutter_active = '#757B84'
      colors.selection_bg = '#2c303f'
      colors.selection_inactive = '#23344B'
      colors.selection_border = '#232A4C'
      colors.guide_active = '#444A55'
      colors.guide_normal = '#323843'

      colors.vcs_added = '#87D96C'
      colors.vcs_modified = '#80BFFF'
      colors.vcs_removed = '#F27983'

      colors.vcs_added_bg = '#313D37'
      colors.vcs_removed_bg = '#3E373A'

      colors.fg_idle = '#707A8C'

      colors.black = '#0A0000'
      colors.red = '#F06B5C'
      colors.green = '#BFE76D'
      colors.yellow = '#E6B752'
      colors.blue = '#3BBBF4'
      colors.magenta = '#D09FFD'
      colors.cyan = '#84CEB5'
      colors.white = '#D2D6DC'
      colors.bright_black = '#0A0000'
      colors.bright_red = '#F39184'
      colors.bright_green = '#D5FF80'
      colors.bright_yellow = '#FFCD66'
      colors.bright_blue = '#73D0FF'
      colors.bright_magenta = '#DFBFFF'
      colors.bright_cyan = '#95E6CB'
      colors.bright_white = '#E3E6EA'
    else
      colors.accent = '#E6B450'
      colors.bg = '#10141C'
      colors.fg = '#BFBDB6'
      colors.line = '#161A24'
      colors.ui = '#5A6378'
      colors.ui_bg = '#0D1017'
      colors.ui_line = '#1B1F29'

      colors.tag = '#39BAE6'
      colors.func = '#FFB454'
      colors.entity = '#59C2FF'
      colors.string = '#AAD94C'
      colors.regexp = '#95E6CB'
      colors.markup = '#F07178'
      colors.keyword = '#FF8F40'
      colors.special = '#E6C08A'
      colors.comment = '#5A6673'
      colors.constant = '#D2A6FF'
      colors.operator = '#F29668'
      colors.error = '#D95757'
      colors.warning = '#FF8F40'
      colors.lsp_parameter = '#CB9FF8'

      colors.panel_bg = '#141821'
      colors.panel_shadow = '#05070A'
      colors.panel_border = '#000000'
      colors.gutter_normal = '#454B55'
      colors.gutter_active = '#626975'
      colors.selection_bg = '#1d212b'
      colors.selection_inactive = '#122132'
      colors.selection_border = '#304357'
      colors.guide_active = '#3C414A'
      colors.guide_normal = '#1E222A'

      colors.vcs_added = '#70BF56'
      colors.vcs_modified = '#73B8FF'
      colors.vcs_removed = '#F26D78'

      colors.vcs_added_bg = '#1D2214'
      colors.vcs_removed_bg = '#2D2220'

      colors.fg_idle = '#565B66'

      colors.black = '#0A0000'
      colors.red = '#E6495A'
      colors.green = '#97C142'
      colors.yellow = '#E89D37'
      colors.blue = '#17ACF2'
      colors.magenta = '#C385FE'
      colors.cyan = '#84CEB5'
      colors.white = '#FFFFFF'
      colors.bright_black = '#0A0000'
      colors.bright_red = '#F07178'
      colors.bright_green = '#AAD94C'
      colors.bright_yellow = '#FFB454'
      colors.bright_blue = '#59C2FF'
      colors.bright_magenta = '#D2A6FF'
      colors.bright_cyan = '#95E6CB'
      colors.bright_white = '#FFFFFF'
    end
  else
    colors.accent = '#F29718'
    colors.bg = '#FCFCFC'
    colors.fg = '#5C6166'
    colors.line = '#edeef1'
    colors.ui = '#F8F9FA'
    colors.ui_fg = '#828E9F'
    colors.ui_line = '#e8e9ec'

    colors.tag = '#55B4D4'
    colors.func = '#EBA400'
    colors.entity = '#22A4E6'
    colors.string = '#86B300'
    colors.regexp = '#4CBF99'
    colors.markup = '#F07171'
    colors.keyword = '#FA8532'
    colors.special = '#E59645'
    colors.comment = '#ABADB1'
    colors.constant = '#A37ACC'
    colors.operator = '#ED9366'
    colors.error = '#E65050'
    colors.warning = '#FA8D3E'
    colors.lsp_parameter = '#C788CE'

    colors.panel_bg = '#FAFAFA'
    colors.panel_shadow = '#EEF0F2'
    colors.panel_border = '#F0F0F0'
    colors.gutter_normal = '#CCCFD3'
    colors.gutter_active = '#A0A6AC'
    colors.selection_bg = '#e5e6ea'
    colors.selection_inactive = '#E7EEF7'
    colors.selection_border = '#E1E1E2'
    colors.guide_active = '#D2D5D8'
    colors.guide_normal = '#E4E6E9'

    colors.vcs_added = '#6CBF43'
    colors.vcs_modified = '#478ACC'
    colors.vcs_removed = '#FF7383'

    colors.vcs_added_bg = '#E0E7CD'
    colors.vcs_removed_bg = '#F9EBE4'

    colors.fg_idle = '#8A9199'

    colors.black = '#86878C'
    colors.red = '#F07171'
    colors.green = '#86B300'
    colors.yellow = '#EBA400'
    colors.blue = '#22A4E6'
    colors.magenta = '#A37ACC'
    colors.cyan = '#4CBF99'
    colors.white = '#ADAEB1'
    colors.bright_black = '#939498'
    colors.bright_red = '#F07171'
    colors.bright_green = '#86B300'
    colors.bright_yellow = '#EBA400'
    colors.bright_blue = '#22A4E6'
    colors.bright_magenta = '#A37ACC'
    colors.bright_cyan = '#4CBF99'
    colors.bright_white = '#C5C5C8'
  end
end

return colors
